baseURL = "https://blog.samrhea.com/"
languageCode = "en-us"
title = "Sam Rhea's blog"
theme = "hugo-cactus-theme-avatar-mod"

[params]
        name = "Sam Rhea"
        description = "Sam Rhea's blog"
        bio = "Texan in Portugal."
        # Enter optionally your twitter account
        twitter = "LakeAustinBlvd"
        enableRSS = true
        avatar = "/static/avatar/avatar.png"
        customCSS = []
        customJS  = []

        # Navigation links
        home = ""
        subscribe = "RSS Feed"
        # Pagination links
        paginate = ""
        olderPosts = ""
        newerPosts = ""
        readMore = ""
        copyright = ""
        # Sharing options and author information in posts
        aboutAuthor = "A Texan in Portugal"
        tweet = ""
        share = ""
        # 404 page
        title404 = ""
        subtitle404 = ""

        # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
        iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/LakeAustinBlvd"
    github = "https://github.com/TownLake/"
