name: Deploy to Workers Staging

on:
  push:
    branches:
      - 'draft/*'

env:
  HUGO_VERSION: 0.71.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Download Hugo
        run: sudo wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Install Hugo
        run: sudo dpkg -i hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Install Wrangler
        run: sudo npm i @cloudflare/wrangler -g

      - name: Build
        run: hugo --environment staging

      - name: config wrangler
        run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish --env staging
